### ISSUE TITLE
无法修改图标，名字等

### ISSUE THREAD

**Issue by cangming99** [cumany/obsidian-editing-toolbar#1]
只要我一点击就会触发拖动，无法进行修改图标等操作

**Comment by cumany** [comment]
你是哪个ob版本？ 我在0.15.9 上测试是没问题的 0.16 我还没办法进行测试。

**Comment by cangming99** [comment]
> 你是哪个ob版本？ 我在0.15.9 上测试是没问题的 0.16 我还没办法进行测试。

0.15.9，我公司的电脑同版本可以用，家里的不行，我回去再看看吧，会不会是什么插件冲突了
