### ISSUE TITLE
Obsidian 在 [V0.14]已经默认增加标注块功能，建议增加相应快捷按钮

### ISSUE THREAD

**Issue by anonymous12357** [cumany/obsidian-editing-toolbar#11]
建议增加 标注块 快捷按钮
 Obsidian 在 [V0.14](https://forum.obsidian.md/t/obsidian-release-v0-14-0-insider-build/33986) 版本中引入的 Admonitions 功能，中文译为「[标注块](https://forum-zh.obsidian.md/t/topic/5493)」，功能灵感来自于插件 Admonition ，官方在 V0.14 版本将它内置了。

「标注块」功能最常用的就是在笔记中将「关键内容」或「重点内容」进行「标注」，如图：
![image](https://user-images.githubusercontent.com/50443017/191651806-547134db-70da-470e-a638-914f32c3fa37.png)

**Comment by cumany** [comment]
插件没有内置因为 系统已经自带这个命令 手动添加进去就可以了。
当然，示例库有已经添加好的模板。
![image](https://user-images.githubusercontent.com/42957010/191652142-44dc77dc-204a-4668-9ed4-7a945bd2238a.png)
![image](https://user-images.githubusercontent.com/42957010/191652214-01123a46-b2bb-4072-8f1a-97f4b06f64e1.png)

**Comment by anonymous12357** [comment]
@cumany 系统已经自带这个命令 手动添加进去就可以了？这是什么意思，obisidian 没有自带Admonitions 插件
![image](https://user-images.githubusercontent.com/50443017/192248545-18696824-1598-47ea-864f-be71a28d3479.png)

**Comment by cumany** [comment]
说错了 是Admonitions 插件自带插入命令 安装Admonitions 插件插件后 把命令添加到 editing toolbar 即可
