### ISSUE TITLE
toolbar设置为top位置时个别主题看不到

### ISSUE THREAD

**Issue by devtint** [cumany/obsidian-editing-toolbar#12]
![image](https://user-images.githubusercontent.com/28558522/191658948-29aa49f1-e6f8-44d2-b143-6f16dfd53a8c.png)
比如这个sodalite 主题这样。它也占用了顶部。可以考虑选择top位置时手动自定义偏移量

**Comment by cumany** [comment]
https://user-images.githubusercontent.com/42957010/192146269-84aed47d-a7cc-435e-871c-144d080d8b0f.png

2.1.2 增加了这个功能 状态栏图标即可调节
