### ISSUE TITLE
Empty lines disappear

### ISSUE THREAD

**Issue by javiavid** [cumany/obsidian-editing-toolbar#13]
**Describe the bug**
When you delete the highlights, the empty lines disappear

**To Reproduce**
Video attachment

**Expected behavior**
Empty lines should be kept

**Screenshots**

https://user-images.githubusercontent.com/7627504/191669888-59b064cb-4d68-437c-8d42-ccdfd85dbc25.mp4

**Desktop (please complete the following information):**
 - OS: windows 11
 - Obisian Version 0.16.3
 - Plugin Version 2.1.1

**Comment by cumany** [comment]
2.1.2  is fixed

**Comment by javiavid** [comment]
Thanks
