### ISSUE TITLE
Shortcuts for highlights

### ISSUE THREAD

**Issue by javiavid** [cumany/obsidian-editing-toolbar#14]
**Is your feature request related to a problem? Please describe.**
I love your plugin for easy text highlighting thanks to the format brush buttons and the clear text formatting button. I think being able to have these 2 buttons in shortcuts would be very useful, so I could program them into my extra mouse buttons or a pencil.

**Describe the solution you'd like**
I propose 3 shortcuts:
1-Activate format brush
2-Activate clear text formatting
3-Disable format brush and clear text formatting (with one single shortcut)

![image](https://user-images.githubusercontent.com/7627504/192157497-05534b24-8815-412c-83de-c57c7feb4671.png)

**Comment by cumany** [comment]
2.1.5 
Add a new command. OFF the format brush. 
Now if nothing is selected, running the Change font color, or Background color command triggers the formatting brush effect

**Comment by javiavid** [comment]
Thanks!
