### ISSUE TITLE
2.1.5在obsidian0.16.3上没有反应

### ISSUE THREAD

**Issue by LJames123** [cumany/obsidian-editing-toolbar#16]
点击工具栏没有任何反应

**Comment by cumany** [comment]
我还没有在0.16上测试 等公开发布后我会检查一下

**Comment by chenxin0397** [comment]
最新版的插件自带的功能（文字加粗等功能）失效，只有自己添加的功能还能用。我用OB的是0.15.9

**Comment by cumany** [comment]
好的 可能跟我修改插件id有关 稍后我重新发布一个新版本

**Comment by cumany** [comment]
新版本已发布 注意看 #17  的说明。
具体到你的问题，应该是插件目录下的data.json 保存的还是旧的插件id 批量替换下就可以恢复功能。

1.  找到插件目录`.obsidian\plugins\editing-toolbar` 
2.  用记事本打开 `data.json` 批量把里面的 `obsidian-editing-toolbar`替换为`editing-toolbar`

**Comment by chenxin0397** [comment]
有些自定义的命令的图标丢失，比如深色模式我用的MOON，现在功能还在，只是没有图标，看上去就像没有按钮
