### ISSUE TITLE
希望设置面板中的submenu能折叠一下

### ISSUE THREAD

**Issue by chenxin0397** [cumany/obsidian-editing-toolbar#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
新增的功能总是排在最后，要加到前面的submenu里需要经过很多个submenu，有些不便

**Comment by chenxin0397** [comment]
新增的功能总是排在最后，要加到前面的submenu里需要经过很多个submenu，有些不便
发完需求之后又有新发现，添加新命令从一个submenu往另一个submenu里移动时，有一定机率会被挤回来。

**Comment by cumany** [comment]
submenu 里的命令是不允许 调整到另一个 submenu中
正确做法 submenu中的命令先移到外部，然后在移动到submenu中。

另外 新增功能 默认在最后可以添加后放子菜单中一起 移动上去。
增加折叠 改动量比较大，近期不做调整。
