### ISSUE TITLE
toolbar设置为fix以后全屏不显示

### ISSUE THREAD

**Issue by cherlas** [cumany/obsidian-editing-toolbar#19]
ob是0.16.3版本

**Comment by cumany** [comment]
2.1.7 fixed

**Comment by zhouxinghong** [comment]
> ob是0.16.3版本

请问您的0.16.3版本安装包可以分享一下吗？让我们用于插件测试。。。

**Comment by cumany** [comment]
我作为插件开发者还没有0.16.3呢 你想啥呢

**Comment by zhouxinghong** [comment]
您可以让上面的兄台分享一下给您，就可以加快插件的开发速度了。。。

**Comment by zhouxinghong** [comment]
> 我作为插件开发者还没有0.16.3呢 你想啥呢

都是社区贡献者。。。
