### ISSUE TITLE
有些自定义的命令的图标丢失，比如深色模式我用的MOON，现在功能还在，只是没有图标，看上去就像没有按钮

### ISSUE THREAD

**Issue by chenxin0397** [cumany/obsidian-editing-toolbar#20]
有些自定义的命令的图标丢失，比如深色模式我用的MOON，现在功能还在，只是没有图标，看上去就像没有按钮
![image](https://user-images.githubusercontent.com/73974352/192841894-76d8b59f-0da8-4a49-979c-749f5e10d1d3.png)

_Originally posted by @chenxin0397 in https://github.com/cumany/obsidian-editing-toolbar/issues/16#issuecomment-1260396069_

**Comment by cumany** [comment]
两个解决办法
1. 点击感叹号 自己重新指定图标
2. 删除data.json 插件会自动创建默认图标。

**Comment by chenxin0397** [comment]
是不是图标的ID被改过了？
我只是担心不稳定，需要反复改

**Comment by cumany** [comment]
是的 因为插件目前还在审核期，目前根据官方初步审核意见，删除了插件内置的部分图标。
