### ISSUE TITLE
不支持quickadd的capture，无法获取选取内容

### ISSUE THREAD

**Issue by Alex-coder251** [cumany/obsidian-editing-toolbar#21]
我用quickadd通过capture把选取段落生成callouts格式，直接用quickadd的命令是可以，但把命令添加到工具栏上点击运行的话就无法获取选取内容只会生成callouts的框😭

**Comment by Alex-coder251** [comment]
补充一下，这是我用的quickadd模板
```
<%*
let selection = window.getSelection();
let choice = await tp.system.suggester(
  [ "✏️ note", "📘 abstract", "ℹ️ info", "🔥 tip", "✅ success", 
  "❓ question", "⚠️ warning", "❌ fail", "🪲 bug", "📋 example", 
  "✍️ quote", "💡 comment", "😝 LOL" ], 
  [ 0,1,2,3,4,5,6,7,8,9,10,11,12 ]
  );
const admonitions = [ 
  ["note", "重点"], ["tip", "摘要"], ["info", "信息"], ["tip", "技巧"], ["success", "完成"], 
  ["question", "问题"], ["warning", "警告"], ["fail", "失败"], ["error", "错误"], ["example", "范例"], 
  ["quote", "引用"], ["comment", "建议"], ["LOL", "好笑"]
];

admonition = admonitions[choice][0];
title = admonitions[choice][1];

const nl = String.fromCharCode(10);

choice = "> [!" + admonition + "] " + title + nl +
  "> " + selection + nl + nl;
%>
<% choice %>
```

**Comment by cumany** [comment]
> 补充一下，这是我用的quickadd模板
> 
> ```
> <%*
> let selection = window.getSelection();
> let choice = await tp.system.suggester(
>   [ "✏️ note", "📘 abstract", "ℹ️ info", "🔥 tip", "✅ success", 
>   "❓ question", "⚠️ warning", "❌ fail", "🪲 bug", "📋 example", 
>   "✍️ quote", "💡 comment", "😝 LOL" ], 
>   [ 0,1,2,3,4,5,6,7,8,9,10,11,12 ]
>   );
> const admonitions = [ 
>   ["note", "重点"], ["tip", "摘要"], ["info", "信息"], ["tip", "技巧"], ["success", "完成"], 
>   ["question", "问题"], ["warning", "警告"], ["fail", "失败"], ["error", "错误"], ["example", "范例"], 
>   ["quote", "引用"], ["comment", "建议"], ["LOL", "好笑"]
> ];
> 
> admonition = admonitions[choice][0];
> title = admonitions[choice][1];
> 
> const nl = String.fromCharCode(10);
> 
> choice = "> [!" + admonition + "] " + title + nl +
>   "> " + selection + nl + nl;
> %>
> <% choice %>
> ```

因为你在点击工具栏的时候鼠标焦点已经转移，所以无法获取焦点所在位置的选中内容。自然你的命令也无法成功运行了。
解决办法
把 `let selection = window.getSelection();` 更换为 `const selection = tp.file.selection();`

**Comment by Alex-coder251** [comment]
谢谢解答

> > 补充一下，这是我用的quickadd模板
> > ```
> > <%*
> > let selection = window.getSelection();
> > let choice = await tp.system.suggester(
> >   [ "✏️ note", "📘 abstract", "ℹ️ info", "🔥 tip", "✅ success", 
> >   "❓ question", "⚠️ warning", "❌ fail", "🪲 bug", "📋 example", 
> >   "✍️ quote", "💡 comment", "😝 LOL" ], 
> >   [ 0,1,2,3,4,5,6,7,8,9,10,11,12 ]
> >   );
> > const admonitions = [ 
> >   ["note", "重点"], ["tip", "摘要"], ["info", "信息"], ["tip", "技巧"], ["success", "完成"], 
> >   ["question", "问题"], ["warning", "警告"], ["fail", "失败"], ["error", "错误"], ["example", "范例"], 
> >   ["quote", "引用"], ["comment", "建议"], ["LOL", "好笑"]
> > ];
> > 
> > admonition = admonitions[choice][0];
> > title = admonitions[choice][1];
> > 
> > const nl = String.fromCharCode(10);
> > 
> > choice = "> [!" + admonition + "] " + title + nl +
> >   "> " + selection + nl + nl;
> > %>
> > <% choice %>
> > ```
> 
> 因为你在点击工具栏的时候鼠标焦点已经转移，所以无法获取焦点所在位置的选中内容。自然你的命令也无法成功运行了。 解决办法 把 `let selection = window.getSelection();` 更换为 `const selection = tp.file.selection();`

谢谢解答！
