### ISSUE TITLE
Can't find this plugin in Obsidian's Community Plugins catalog

### ISSUE THREAD

**Issue by erohtar** [cumany/obsidian-editing-toolbar#22]
**Describe the bug**
This looks like a very nice plugin, but I can't find it in Obsidian's Community Plugins catalog.

**To Reproduce**
Go into Obsidian's settings > Community plugins and search for 'Editing' or 'Toolbar'

**Comment by cumany** [comment]
I have submitted the official community store more than a month ago, but the official has not yet reviewed, I believe that after the review will be searched in Obsidian's Community Plugins

**Comment by erohtar** [comment]
Oh okay, got it. 

It's a very helpful plugin and even though people say "just learn markdown", I think this helps with that too as you can use the toolbar to instantly generate the needed markdown and then study it right there, instead of the usual (slower) way of going to your reference material, finding the necessary formatting method and study there, then come back and apply it.

I hope it's approved soon - in the meantime, I've enabled watching this project for releases :)

**Comment by XMB-7** [comment]
You could use an awesome Obsidian plugin named "Obsidian42 - BRAT" to install and manage any in-testing Obsidian plugin still not being reviewed. 
It is always the recommended way to install plugins that are not included yet in the plugin store.

**Comment by erohtar** [comment]
That's pretty cool! I just added it, and added your plugin to its monitored list - now do I keep the folder for your plugin that I created manually, or delete that and let BRAT take over?

**Comment by XMB-7** [comment]
Just delete what you created and let BRAT take over.

**Comment by erohtar** [comment]
Done - thank you so much for your help!

**Comment by MMoMM-org** [comment]
it is now available via the Catalog
