### ISSUE TITLE
微调子菜单的显示位置, 缩减鼠标移动距离

### ISSUE THREAD

**Issue by XMB-7** [cumany/obsidian-editing-toolbar#24]
如图所示,
![image](https://user-images.githubusercontent.com/65625632/195894381-de305e53-8100-4bcd-b280-0cfda3ea6414.png)
如果子菜单能与母图标呈中心对称分布, 亦即Hn对齐H3和H4间的中线, 那么鼠标点选第一个子命令所需要的移动距离就大大降低了, 这样使鼠标点选每一个子命令所需要移动的距离都不太长, 用起来就会更舒服.

**Comment by cumany** [comment]
2.2.0 版本 已经调整

**Comment by HoGafi** [comment]
H1离左侧是没空的，H6离右侧还有空，对这种能修复不？

**Comment by HoGafi** [comment]
@cumany
