### ISSUE TITLE
emoji toolbar嵌入无法正常插入

### ISSUE THREAD

**Issue by yixiaofan1** [cumany/obsidian-editing-toolbar#26]
我在Editing Toolbar添加了Emoji Toolbar: Open emoji picker这个命令的。
点击之后能够弹出Emoji的选择框，选择一个图标之后，没有正确的插入。
用命令调出Emoji Toolbar: Open emoji picker能够正常的工作。

Emoji Toolbar的版本是0.3.2
Editing Toolbar的版本是2.2.0
Obsidian的版本是1.0。0

**Comment by cumany** [comment]
emoji插件的问题 我已经修复 下载示例库的插件即可解决。
https://github.com/cumany/Blue-topaz-examples/tree/main/.obsidian/plugins/obsidian-emoji-toolbar
