### ISSUE TITLE
Codeblock focus is faulty

### ISSUE THREAD

**Issue by yefengwu** [cumany/obsidian-editing-toolbar#27]
When I created codeblcok using the editing toolbar shortcut command, it was at the end of its focus and needed to be readjust.
![GIF 2022-10-24 18-20-13](https://user-images.githubusercontent.com/45461486/197505279-d757fa0f-deb2-4d35-807e-2d72cd6e609a.gif)

**Comment by cumany** [comment]
2.2.1 fixed

**Comment by yefengwu** [comment]
Great!
