### ISSUE TITLE
Selected text automatically colors it when color option was used previously

### ISSUE THREAD

**Issue by Lagann311** [cumany/obsidian-editing-toolbar#28]
**Describe the bug**
Sometimes when selecting text, it automatically adds the inline css around it.

**Expected behavior**
Selecting text alone shouldn't trigger the color text action.

**Screenshots**
![coloring-bug](https://user-images.githubusercontent.com/51365335/199052758-b08bedb2-846d-4a7a-be66-b84dd619fa4d.gif)

/e I'm not sure if this is intended for ease of us, but if it is, maybe an option in settings can be added to not trigger the action automatically.

**Comment by cumany** [comment]
Sorry for taking so long to reply to the message.
should trigger the font color formatting brush operation.
The design logic of the formatting brush is like this

- If you select the text first and then set the color, it should be normal.

- If you set the color first and then select the text, this will trigger the formatting brush, and the next selected text will also trigger. You can't cancel the formatting brush unless you press the right or middle mouse button, or click on another area of the note.
