### ISSUE TITLE
使用插件web browser在ob内打开链接, 所有已打开页面中的插件栏都会消失

### ISSUE THREAD

**Issue by XMB-7** [cumany/obsidian-editing-toolbar#29]
如题, 只要使用插件web browser在ob内打开链接, 所有已打开页面中的插件栏就都会消失(我用的tiny显示模式),  此时需要手动关开显隐才能将之重新调出, 或者打开一个新的页面才能使之正常化.
![image](https://user-images.githubusercontent.com/65625632/200127204-a0111bb6-a2f5-47be-8cbd-d74ce4d6d64e.png)

希望能对此优化一下, 感谢.

**Comment by cumany** [comment]
收到，下个版本修复

**Comment by cumany** [comment]
2.2.1 fixed
