### ISSUE TITLE
Spacing/positioning issue for "Background color", "Font Colors" and "Headings" when using other position than top.

### ISSUE THREAD

**Issue by Gentleman03** [cumany/obsidian-editing-toolbar#3]
**Describe the bug**
There is some issue with spacing for "Background color", "Font Colors" and "Headings" when using other position than top.

**To Reproduce**
1. Go to Plugin Settings
2. Editing toolbar position from top to fixed of rollowing (btw. there is misspeling "posotion"

**Expected behavior**
Whole field of icon should be hoverable but right now icons are on the right edge of their space and expanding arrow is misplaced. I would remove this arrow and made field clickable/hoverable instead.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/60824838/189486263-82ec33f9-1f64-4183-82dd-edb060b341b6.png)

**Desktop:**
 - Windows 10 pro
 - Obsidian 0.15.9
 - Installator version 0.15.6
 - Theme doesn't matter

**Comment by cumany** [comment]
Thank you for your feedback, please upgrade to the latest and check if the issue has been solved

**Comment by Gentleman03** [comment]
> Thank you for your feedback, please upgrade to the latest and check if the issue has been solved

Yes, it looks good now :)
