### ISSUE TITLE
插件询问

### ISSUE THREAD

**Issue by sevelee** [cumany/obsidian-editing-toolbar#31]
你好，请问这个H1的显示和123的显示是用的什么插件呢？
![image](https://user-images.githubusercontent.com/8036235/201124496-b9c65dbb-b7d1-4cd8-84e2-2d46645b5208.png)

**Comment by cumany** [comment]
123ob设置里开启显示行号即可

h1 是blue topaz 主题自带的效果

**Comment by sevelee** [comment]
![image](https://user-images.githubusercontent.com/8036235/201165321-2c1e07b5-a805-4f99-b307-a9ba7413752c.png)
我也在使用blue topaz，但是看起来和您的图片上的效果很不一样。请问是哪里需要设置一下吗？

**Comment by cumany** [comment]
安装 style settings 插件 在 blue topaz 里面的  2.2.3 选项开启即可
