### ISSUE TITLE
Emoji Toolbar can't insert Emojis

### ISSUE THREAD

**Issue by MMoMM-org** [cumany/obsidian-editing-toolbar#32]
I added the Emoji Toolbar to the Editing Toolbar.
Clicking on the icon brings up the Emoji Toolbar Picker, but after selecting an emoji it is not pasted into the document.
Any idea?

**Comment by cumany** [comment]
The original version of this plugin does not work on the toolbar, so I made some modifications, please download and install the modified plugin in [the example vault](https://github.com/cumany/Blue-topaz-examples/tree/main/.obsidian/plugins/obsidian-emoji-toolbar).

**Comment by MMoMM-org** [comment]
ah, could you not make a pull request to the original plugin to allow this? I don't really want to keep on downloading the plugin from inside the example vault.

**Comment by cumany** [comment]
That makes sense, I have just submitted  the [PR](https://github.com/oliveryh/obsidian-emoji-toolbar/pull/46)

**Comment by MMoMM-org** [comment]
cool, thanks. looking forward to see it implemented.
