### ISSUE TITLE
Cannot read properties of null (reading 'style')     at Nl.handlecMenuToolba

### ISSUE THREAD

**Issue by MMoMM-org** [cumany/obsidian-editing-toolbar#33]
Logs are full with:

app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Nl.handlecMenuToolbar (plugin:editing-toolbar:28:87803)

**Comment by cumany** [comment]
Sorry, I can't locate the error with this information.
Some reproducible steps need to be provided, such as what page you opened that gave this error.

**Comment by MMoMM-org** [comment]
If I close all notes I get that error for sure. Just tested with a quite barebone vault at the moment. https://github.com/MMoMM-org/obsidian-youtube-vault

**Comment by MMoMM-org** [comment]
ah, and if there is no note open and you click then into the sidebars.

**Comment by cumany** [comment]
Sorry for the lack of reply, the new version should have solved the problem, if there are still errors reported please let me know
