### ISSUE TITLE
Question: How do I get THIS?

### ISSUE THREAD

**Issue by merlinuwe** [cumany/obsidian-editing-toolbar#38]
Thanks for your amazing plugin!

But how do i get this?

![image](https://user-images.githubusercontent.com/4138869/201538858-0cec6156-c448-42e0-8659-74fb5a77486d.png)

**Comment by cumany** [comment]
This is a feature of the [commander plugin ](obsidian://show-plugin?id=cmdr) that you can install and add custom commands to the top of the page.
