### ISSUE TITLE
Couple of improvements for flexibility of toolbar

### ISSUE THREAD

**Issue by Gentleman03** [cumany/obsidian-editing-toolbar#4]
- It would be great to have possibility to choose bottom for toolbar position. (And maybe even right and left?)
- Also "Draggable" position would be great, meaning that you could freely drag and drop your toolbar wherever you want.
- Extend editing toolbar columns range because for fixed position 18 columns is not enough.

Thanks for updating this plugin and improving it. Great job!

**Comment by cumany** [comment]
Thank you for your suggestion, the position can be adjusted by css, which is very flexible. I can add a similar option later. As for draggable to any position, it's a bit difficult to do it at the moment. 
Also the number of  editing toolbar columns has been expanded to 32 columns
