### ISSUE TITLE
Hover 显示隐藏菜单栏

### ISSUE THREAD

**Issue by Connor-yang96** [cumany/obsidian-editing-toolbar#44]
自定义css：

```
/*Hover display Toolbar */ 

#cMenuToolbarModalBar.top {
    opacity: 0 !important;    
}

#cMenuToolbarModalBar.top:hover  {
    opacity: 1 !important;    
}
```
![Obsidian_rXGY3SVtdH](https://user-images.githubusercontent.com/81000027/202994609-f9b10fb7-8638-4eaa-b3c6-586cb0e837ca.gif)

如果原生支持这个 ，那更好。

**Comment by cumany** [comment]
新版本（2.2.3）已经支持

**Comment by XMB-7** [comment]
@cumany 试了一下, 效果很棒, 但不知能否再增加一个延迟设置, 比如鼠标悬浮0.5s以上才予以显示, 这样能够避免鼠标简单划过所造成的短暂显隐.
