### ISSUE TITLE
可否增加文章全局复制

### ISSUE THREAD

**Issue by A2Data** [cumany/obsidian-editing-toolbar#46]
类似： http://editor.md.ipandao.com/examples/full.html
https://md.openwrite.cn/
编辑完成之后，可以直接复制，方便发布其他平台

**Comment by cumany** [comment]
ctrl +a    ctrl+c 不就可以全文复制 我估计你说的是 复制渲染后的文章内容
你可以借助这个插件 
https://github.com/mvdkwast/obsidian-copy-as-html
并把命令添加到 toolbar里就可以了
