### ISSUE TITLE
[FR] 对于底部显示模式, 首行的子菜单改在工具栏的上方显示, 以免遮蔽后续的行

### ISSUE THREAD

**Issue by XMB-7** [cumany/obsidian-editing-toolbar#48]
目前子菜单会产生遮蔽:
![image](https://user-images.githubusercontent.com/65625632/204579571-e34f067a-e39f-436e-8c95-0b1d2edbb40b.png)

预期改进效果:
![image](https://user-images.githubusercontent.com/65625632/204580058-98853cb9-e88e-46b7-a2b7-69e9526408ef.png)

**Comment by cumany** [comment]
新版本（2.2.3）已经支持

**Comment by XMB-7** [comment]
感谢, 另外能否对图标所对应的命令名提示框也进行相同的处理, 如图一些长的命令名也会造成遮蔽.
![image](https://user-images.githubusercontent.com/65625632/207542984-1a6624b7-1e21-4e2d-b3e0-81689fcfcd95.png)

**Comment by cumany** [comment]
这个提示栏目前无法控制显示位置， 不过提示栏的内容是可以修改的，设置添加命令的时候修改命令名称就是提示栏的内容，如果名称为空，也就不会显示提示栏了。

**Comment by XMB-7** [comment]
感谢, 这样已经足够好了.
