### ISSUE TITLE
和longfrom一起使用会导致longfrom无法点击打开

### ISSUE THREAD

**Issue by xsdcxsdc** [cumany/obsidian-editing-toolbar#49]
这个，似乎是cMenu就有的问题，有望修改一下吗？

**Comment by cumany** [comment]
特意安装了longfrom插件 没发现问题，可以详细说一下吗

**Comment by xsdcxsdc** [comment]
![ce7b2c818a7fc2089e9b19326c24ee7497f55b6f](https://user-images.githubusercontent.com/107874063/206764259-4b4c15ad-eaa8-479a-887a-a1d6e1157ea1.gif)
↑这样。
中文论坛上有个贴子说了这个。
通常应该是点击就直接打开的，但如果开着cMenu就会变成这样。

**Comment by cumany** [comment]
新版本已经修复

**Comment by xsdcxsdc** [comment]
感谢！
