### ISSUE TITLE
failed to load plugin editing-toolbar

### ISSUE THREAD

**Issue by changxiangyang** [cumany/obsidian-editing-toolbar#54]
**Describe the bug**
Unable to start the plug-in, error msg:  failed to load plugin editing-toolbar

**To Reproduce**
obsidian app version: v.1.1.8 、 v.1.1.3
plug-in version: 2.2.3
When I click the start button, I get an error：failed to load plugin editing-toolbar

**Expected behavior**
1. Why does this error occur? Is there a problem with my local environment?
2. How to solve the problem?

**Screenshots**
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/22831029/208812158-23c5a6a6-a94e-4d89-90ff-d2a8cd6cf67c.png">

**Desktop (please complete the following information):**
 - OS: [macOS monterey 12.3.1]
 - Obsidian Version [v.1.1.8]
 - Plug-in Version [2.2.3]

**Comment by cumany** [comment]
main.js file size is relatively large, may not be downloaded completely, uninstall and re-download, or manually download the file to try

https://github.com/cumany/obsidian-editing-toolbar/releases/download/2.2.3/main.js

**Comment by changxiangyang** [comment]
perfect，NB !!!
