### ISSUE TITLE
Please add "magenta" and "blue (0,0,255)" to font/background color plate for memerization study thx

### ISSUE THREAD

**Issue by ccchan234** [cumany/obsidian-editing-toolbar#61]
**Is your feature request related to a problem? Please describe.**

Cannot / I don't know how to choose magenta color in fonts and background,
also the blue i am not sure is RGB 0,0,255

**Describe the solution you'd like**

Hope these two colors are added to the default color chooser

**Describe alternatives you've considered**

**Additional context**

When on a LCD, magenta text with blue (0,0,255) background could be viewed thru a PHYSICAL green plastic filter. in that way the TEXT is hidden:
![image](https://user-images.githubusercontent.com/37549409/211150799-51d6ff88-ac5e-40df-a986-4e564ec64056.png)

![image](https://user-images.githubusercontent.com/37549409/211150831-2bb70c0d-f088-4350-ae4b-6175034cc4a9.png)

this will help me make obsidian also a "anki" study tool. thanks

**Comment by ccchan234** [comment]
i can manually change the hex color code but it's very painful,
pls try add them to default thanks

magenta: ff00ff
blue: 0000ff

![image](https://user-images.githubusercontent.com/37549409/211151309-0df3e9da-7c63-4b40-9121-fcb42a8d0b8b.png)

**Comment by cumany** [comment]
2.3.0 fixed
