### ISSUE TITLE
[Feature request] Add a way to change colors in the font color menu

### ISSUE THREAD

**Issue by ShugarSkull** [cumany/obsidian-editing-toolbar#65]
**Is your feature request related to a problem? Please describe.**
Colors in the font color picker are of default Microsoft Office and are not allays suited for styling my notes.

**Describe the solution you'd like**
Add a setting (or a file) to manually set a color scheme (either one by one or by other means)

**Describe alternatives you've considered**
I've tried to modify the colors directly in `utils.ts` but it's a very tedious process for little reward, and I need to redo it if I need another color scheme

**Comment by hubmg** [comment]
i came here to submit the same request

**Comment by cumany** [comment]
2.3.0 fixed
