### ISSUE TITLE
开启插件使得obsidian全局的滚动操作变得卡顿。

### ISSUE THREAD

**Issue by F1nnMertens** [cumany/obsidian-editing-toolbar#67]
之前在另一台电脑上obsidian软件使用正常，换电脑后使用软件感到明显卡顿，怀疑是插件问题，
经过控制变量对所有插件逐个开启关闭，发现是本插件的问题。
后又偶然发现将工具栏样式选择默认或简约均会造成卡顿，但选择毛玻璃样式可解决该问题。
翻阅issue列表，发现之前有人提出过该问题，特此提出本人的发现，以期作者未来开发过程中注意。

调试信息：
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v1.1.9
	Operating system: Windows 10 Home China 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: AnuPpuccin v1.2.7
	Snippets enabled: 9
	Restricted mode: off
	Plugins installed: 39
	Plugins enabled: 3
		1: proxy github v1.15.0
		2: Excalidraw v1.8.9
		3: Editing Toolbar v2.2.3

**Comment by wayne3602** [comment]
我也遇到了同样的问题，关闭本插件后流畅的一b

**Comment by F1nnMertens** [comment]
> 

可以暂时用我的那个方法，把工具栏样式改成glass毛玻璃。

**Comment by F1nnMertens** [comment]
> Reference

可以暂时用我的那个方法，把工具栏样式改成glass毛玻璃。

**Comment by cumany** [comment]
2.3.0 优化了

**Comment by yx1024** [comment]
感谢！！！我在使用border主题发现左右关闭侧边栏会触发页面混乱的bug，本来以为是主题的问题，抓了一下性能发现是这个插件的宽度变化重绘的问题，改成毛玻璃一下很流畅！！！一些魔法！
