### ISSUE TITLE
我想增大图标按钮的面积，应该在哪里修改呢

### ISSUE THREAD

**Issue by TusGrid** [cumany/obsidian-editing-toolbar#7]
现在的图标按钮对我而言有点太窄，图标之间空隙比较大，我尝试修改css但失败了，应该修改哪里增加图标按钮面积呢

**Comment by cumany** [comment]
样式可以试着选择 tiny default 或者glass

**Comment by zhaoscsc** [comment]
我是4K的显示器，跟随模式下，感觉优点小，要是再稍微大一些就好了。

**Comment by cumany** [comment]
#35
