### ISSUE TITLE
只支持字体设置为绿色，虽然有选择颜色但是不起作用

### ISSUE THREAD

**Issue by wutongshu85** [cumany/obsidian-editing-toolbar#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wutongshu85** [comment]
只支持字体设置为绿色，虽然有选择颜色但是不起作用

**Comment by wutongshu85** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/49102595/221211497-6c2a1452-5ad2-4f57-97a0-9f82e35f5589.png">

**Comment by zGuangYuan** [comment]
同样的问题，无法修改颜色！！

**Comment by cumany** [comment]
这边无法复现，是不是因为跟其他什么插件冲突了？

**Comment by FranShavee** [comment]
> 这边无法复现，是不是因为跟其他什么插件冲突了？

是table enhancer 插件，开启后不能字体颜色不能更改，具体问题还没找到

**Comment by cumany** [comment]
table enhancer  这个插件在作者已经更新了 用新版应该能解决

**Comment by vivificationLeslie** [comment]
hi 我也出现了同样的问题，但不只是不能修改颜色，我没有任何一个下拉框，且设置菜单中颜色均无法显示。
![image](https://github.com/PKM-er/obsidian-editing-toolbar/assets/24772786/c5d6b555-5005-46a7-a15c-914e240e1c2e)
![image](https://github.com/PKM-er/obsidian-editing-toolbar/assets/24772786/d3332312-3ffc-483e-97da-f56949c0907a)

我没有安装table enhancer 插件，即使在我禁用了所有其他插件的情况下依然没有下拉框。
Obsidian 版本：1.3.7;
Editing Toolbar 版本：2.3.1

十分感谢！

**Comment by vivificationLeslie** [comment]
> hi 我也出现了同样的问题，但不只是不能修改颜色，我没有任何一个下拉框，且设置菜单中颜色均无法显示。 ![image](https://user-images.githubusercontent.com/24772786/260009763-c5d6b555-5005-46a7-a15c-914e240e1c2e.png) ![image](https://user-images.githubusercontent.com/24772786/260009471-d3332312-3ffc-483e-97da-f56949c0907a.png)
> 
> 我没有安装table enhancer 插件，即使在我禁用了所有其他插件的情况下依然没有下拉框。 Obsidian 版本：1.3.7; Editing Toolbar 版本：2.3.1
> 
> 十分感谢！

解决了！是我使用了“Ultra Lobster”这个外观主题的问题，更换后这个问题解决了。打扰了:) 再次感谢！
