### ISSUE TITLE
支持多个toolbar同时存在

### ISSUE THREAD

**Issue by chu-shen** [cumany/obsidian-editing-toolbar#72]
**Is your feature request related to a problem? Please describe.**

支持多个 toolbar 同时存在，比如 following+fixed

高频操作放在 following 中，低频放在 fixed 中：
- 减少鼠标移动距离
- 缩短 following 长度

希望作者能考虑增加这一特性👍

**Additional context**

另外，following 选中文字时，toolbar 是右对齐，能否改为居中？谢谢
![image](https://user-images.githubusercontent.com/45256288/225627439-16c7f69c-dcaf-488b-844a-9c5725e72614.png)

**Comment by cumany** [comment]
1.多个toolbar 同时存在是可以的 修改插件目录的manifest.json文件，复制一份两份manifest.json文件中id不一样即可得到两个toolbar 不想麻烦的话 再安装一个cmenu插件也可以实现。
2. 对齐考虑的因素很多主要靠近边界的时候工具栏会不会溢出

**Comment by chu-shen** [comment]
插件复制了一份，文件夹名修改为`editing-toolbar-2`，manifest改成以下内容
```json
{
	"id": "editing-toolbar-2",
	"name": "Editing Toolbar 2",

}
```

控制台可以看到加载了两次：
```
plugin:editing-toolbar:3480 cMenuToolbar v2.3.1 loaded
plugin:cm-chs-patch:7 Jieba loaded
plugin:cm-chs-patch:7 editor word splitting patched
plugin:editing-toolbar-2:9 cMenuToolbar v2.3.1 loaded
```

但页面只有一个toolbar，是不是哪里修改错了，两个冲突了？

原版的cmenu装了，但是没子菜单，像对齐功能就会占用四格🥲

**Comment by cumany** [comment]
我意识到了这个问题 因为用的插件class类是一样的 所以简单更改id 还是无法渲染出两个。

**Comment by cumany** [comment]
目前从插件逻辑上支持多开是比较复杂的，更改的话 可能要在插件js 上批量替换cMenuToolbarModalBar 这个估计才可以

**Comment by chu-shen** [comment]
> 目前从插件逻辑上支持多开是比较复杂的，更改的话 可能要在插件js 上批量替换cMenuToolbarModalBar 这个估计才可以

方法可行，感谢👍

之前尝试过替换`cMenuToolbarModalBar`，不过没成功，现在才发现js里还有😂

---

多开步骤：
1. 复制一份插件文件夹，改名为`editing-toolbar-2`，并启用
2. 修改`manifest.json`中id为`editing-toolbar-2`
3. 替换`main.js`和`styles.css`中的`cMenuToolbarModalBar`为`cMenuToolbarModalBar2`
