### ISSUE TITLE
Close Editing Toolbar on escape pressed

### ISSUE THREAD

**Issue by MSzturc** [cumany/obsidian-editing-toolbar#8]
I would like to close the following editing bar on escape press, since there are situations where the bar is rendered ontop of an item i want to edit

**Comment by cumany** [comment]
The  following editing bar will be displayed only when the text is selected ,  you mean  pressing esc can hide the toolbar when select the text?

**Comment by cumany** [comment]
Indeed, for the toolbar it pops up as soon as you select the text. Hmm, I might consider adding a shortcut to quickly hide the  toolbar

**Comment by cumany** [comment]
I added a new feature to listen for key events to dismiss the toolbar

> I would like to close the following editing bar on escape press, since there are situations where the bar is rendered ontop of an item i want to edit

This feature has been added. Just update it

**Comment by MSzturc** [comment]
Big thx, works as expected! Btw. one last question. I've noticed that there is a delay between an input and the response of the toolbar. Is this delay needed to work properly or would it be possible to make it configurable? I like me tools to feel snappy, delays made me feel that something is wrong and create the desire to open task manger and have a look if there is a process that is going crazy.

**Comment by cumany** [comment]
What you mean is that the toolbar displays a bit delayed when the text is selected. In fact, there is indeed a css animation effect that delays about 0.5 seconds

**Comment by MSzturc** [comment]
ahh thx solved this issue by a css snippet, thx for you help
