### ISSUE TITLE
Not longer able to click on Submenu with 2.1.0

### ISSUE THREAD

**Issue by MSzturc** [cumany/obsidian-editing-toolbar#9]
https://user-images.githubusercontent.com/4275753/190150238-3d0e31fe-bff0-4b0a-894b-a7aa3ad03899.mov

**Comment by cumany** [comment]
Can you provide the version of OBSIDIAN and what theme you are using, since I can't reproduce your issue

**Comment by MSzturc** [comment]
I use 15.9 on macos. Tried it with Shimmering Focus and with the standard theme (also deactivated all my css snippets)

**Comment by cumany** [comment]
This may be a issue of compatibility between css and sarafi, I'll provide a css for you . If the issues are solved I'll push a new update.
Put the `styles.css` file from the zip in the `.obsidian\plugins\obsidian-editing-toolbar` directory to overwrite , then restart ob.

[styles.zip](https://github.com/cumany/obsidian-editing-toolbar/files/9567319/styles.zip)

**Comment by MSzturc** [comment]
No doesnt work either

I've done a bit debugging and it seams that it's a problem with the height of the toolbar. You have to wrap the toolbar into a container div that's height should be 80px and that is invisible and with a child div that contains all buttons and that has a height of 40px and the layout of the bar.

**Comment by cumany** [comment]
In flowing mode, the setting of Editing Toolbar columns does affect the toolbar height, and it is recommended to set a larger value.

**Comment by MSzturc** [comment]
Yeah it was tricky by i've made it working with a couple css modifications. Thx for your effort
